// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// sum request and response
type SumRequest struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{0}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *SumRequest) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type SumResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{1}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// div request and response
type DivRequest struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DivRequest) Reset()         { *m = DivRequest{} }
func (m *DivRequest) String() string { return proto.CompactTextString(m) }
func (*DivRequest) ProtoMessage()    {}
func (*DivRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{2}
}

func (m *DivRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DivRequest.Unmarshal(m, b)
}
func (m *DivRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DivRequest.Marshal(b, m, deterministic)
}
func (m *DivRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DivRequest.Merge(m, src)
}
func (m *DivRequest) XXX_Size() int {
	return xxx_messageInfo_DivRequest.Size(m)
}
func (m *DivRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DivRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DivRequest proto.InternalMessageInfo

func (m *DivRequest) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *DivRequest) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type DivResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DivResponse) Reset()         { *m = DivResponse{} }
func (m *DivResponse) String() string { return proto.CompactTextString(m) }
func (*DivResponse) ProtoMessage()    {}
func (*DivResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{3}
}

func (m *DivResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DivResponse.Unmarshal(m, b)
}
func (m *DivResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DivResponse.Marshal(b, m, deterministic)
}
func (m *DivResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DivResponse.Merge(m, src)
}
func (m *DivResponse) XXX_Size() int {
	return xxx_messageInfo_DivResponse.Size(m)
}
func (m *DivResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DivResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DivResponse proto.InternalMessageInfo

func (m *DivResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// multiply request and response
type MultiplyRequest struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiplyRequest) Reset()         { *m = MultiplyRequest{} }
func (m *MultiplyRequest) String() string { return proto.CompactTextString(m) }
func (*MultiplyRequest) ProtoMessage()    {}
func (*MultiplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{4}
}

func (m *MultiplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplyRequest.Unmarshal(m, b)
}
func (m *MultiplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplyRequest.Marshal(b, m, deterministic)
}
func (m *MultiplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplyRequest.Merge(m, src)
}
func (m *MultiplyRequest) XXX_Size() int {
	return xxx_messageInfo_MultiplyRequest.Size(m)
}
func (m *MultiplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplyRequest proto.InternalMessageInfo

func (m *MultiplyRequest) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *MultiplyRequest) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type MultiplyResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiplyResponse) Reset()         { *m = MultiplyResponse{} }
func (m *MultiplyResponse) String() string { return proto.CompactTextString(m) }
func (*MultiplyResponse) ProtoMessage()    {}
func (*MultiplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{5}
}

func (m *MultiplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplyResponse.Unmarshal(m, b)
}
func (m *MultiplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplyResponse.Marshal(b, m, deterministic)
}
func (m *MultiplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplyResponse.Merge(m, src)
}
func (m *MultiplyResponse) XXX_Size() int {
	return xxx_messageInfo_MultiplyResponse.Size(m)
}
func (m *MultiplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplyResponse proto.InternalMessageInfo

func (m *MultiplyResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// sub request and response
type SubRequest struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubRequest) Reset()         { *m = SubRequest{} }
func (m *SubRequest) String() string { return proto.CompactTextString(m) }
func (*SubRequest) ProtoMessage()    {}
func (*SubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{6}
}

func (m *SubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubRequest.Unmarshal(m, b)
}
func (m *SubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubRequest.Marshal(b, m, deterministic)
}
func (m *SubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubRequest.Merge(m, src)
}
func (m *SubRequest) XXX_Size() int {
	return xxx_messageInfo_SubRequest.Size(m)
}
func (m *SubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubRequest proto.InternalMessageInfo

func (m *SubRequest) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *SubRequest) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type SubResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubResponse) Reset()         { *m = SubResponse{} }
func (m *SubResponse) String() string { return proto.CompactTextString(m) }
func (*SubResponse) ProtoMessage()    {}
func (*SubResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{7}
}

func (m *SubResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubResponse.Unmarshal(m, b)
}
func (m *SubResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubResponse.Marshal(b, m, deterministic)
}
func (m *SubResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubResponse.Merge(m, src)
}
func (m *SubResponse) XXX_Size() int {
	return xxx_messageInfo_SubResponse.Size(m)
}
func (m *SubResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubResponse proto.InternalMessageInfo

func (m *SubResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type PrimeNumberCompositionRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberCompositionRequest) Reset()         { *m = PrimeNumberCompositionRequest{} }
func (m *PrimeNumberCompositionRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberCompositionRequest) ProtoMessage()    {}
func (*PrimeNumberCompositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{8}
}

func (m *PrimeNumberCompositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberCompositionRequest.Unmarshal(m, b)
}
func (m *PrimeNumberCompositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberCompositionRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNumberCompositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberCompositionRequest.Merge(m, src)
}
func (m *PrimeNumberCompositionRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberCompositionRequest.Size(m)
}
func (m *PrimeNumberCompositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberCompositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberCompositionRequest proto.InternalMessageInfo

func (m *PrimeNumberCompositionRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeNumberCompositionResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberCompositionResponse) Reset()         { *m = PrimeNumberCompositionResponse{} }
func (m *PrimeNumberCompositionResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberCompositionResponse) ProtoMessage()    {}
func (*PrimeNumberCompositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{9}
}

func (m *PrimeNumberCompositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberCompositionResponse.Unmarshal(m, b)
}
func (m *PrimeNumberCompositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberCompositionResponse.Marshal(b, m, deterministic)
}
func (m *PrimeNumberCompositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberCompositionResponse.Merge(m, src)
}
func (m *PrimeNumberCompositionResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberCompositionResponse.Size(m)
}
func (m *PrimeNumberCompositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberCompositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberCompositionResponse proto.InternalMessageInfo

func (m *PrimeNumberCompositionResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type ComputeAvgRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeAvgRequest) Reset()         { *m = ComputeAvgRequest{} }
func (m *ComputeAvgRequest) String() string { return proto.CompactTextString(m) }
func (*ComputeAvgRequest) ProtoMessage()    {}
func (*ComputeAvgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{10}
}

func (m *ComputeAvgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeAvgRequest.Unmarshal(m, b)
}
func (m *ComputeAvgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeAvgRequest.Marshal(b, m, deterministic)
}
func (m *ComputeAvgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeAvgRequest.Merge(m, src)
}
func (m *ComputeAvgRequest) XXX_Size() int {
	return xxx_messageInfo_ComputeAvgRequest.Size(m)
}
func (m *ComputeAvgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeAvgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeAvgRequest proto.InternalMessageInfo

func (m *ComputeAvgRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type ComputeAvgResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeAvgResponse) Reset()         { *m = ComputeAvgResponse{} }
func (m *ComputeAvgResponse) String() string { return proto.CompactTextString(m) }
func (*ComputeAvgResponse) ProtoMessage()    {}
func (*ComputeAvgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{11}
}

func (m *ComputeAvgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeAvgResponse.Unmarshal(m, b)
}
func (m *ComputeAvgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeAvgResponse.Marshal(b, m, deterministic)
}
func (m *ComputeAvgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeAvgResponse.Merge(m, src)
}
func (m *ComputeAvgResponse) XXX_Size() int {
	return xxx_messageInfo_ComputeAvgResponse.Size(m)
}
func (m *ComputeAvgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeAvgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeAvgResponse proto.InternalMessageInfo

func (m *ComputeAvgResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "calculator.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "calculator.SumResponse")
	proto.RegisterType((*DivRequest)(nil), "calculator.DivRequest")
	proto.RegisterType((*DivResponse)(nil), "calculator.DivResponse")
	proto.RegisterType((*MultiplyRequest)(nil), "calculator.MultiplyRequest")
	proto.RegisterType((*MultiplyResponse)(nil), "calculator.MultiplyResponse")
	proto.RegisterType((*SubRequest)(nil), "calculator.SubRequest")
	proto.RegisterType((*SubResponse)(nil), "calculator.SubResponse")
	proto.RegisterType((*PrimeNumberCompositionRequest)(nil), "calculator.PrimeNumberCompositionRequest")
	proto.RegisterType((*PrimeNumberCompositionResponse)(nil), "calculator.PrimeNumberCompositionResponse")
	proto.RegisterType((*ComputeAvgRequest)(nil), "calculator.ComputeAvgRequest")
	proto.RegisterType((*ComputeAvgResponse)(nil), "calculator.ComputeAvgResponse")
}

func init() {
	proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor_7f42938f8c8365cf)
}

var fileDescriptor_7f42938f8c8365cf = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x49, 0x4f, 0xf2, 0x40,
	0x18, 0xa6, 0x1f, 0xf9, 0x88, 0x79, 0x41, 0xc5, 0x39, 0x54, 0x53, 0x85, 0x68, 0x8d, 0x09, 0xa2,
	0x41, 0xa3, 0x07, 0xb9, 0x2a, 0x24, 0x9e, 0x5c, 0x42, 0xbd, 0xe8, 0xc5, 0x30, 0x75, 0x34, 0x93,
	0xb4, 0x9d, 0x3a, 0x4b, 0x13, 0x7f, 0xa5, 0x7f, 0xc9, 0xd0, 0x25, 0x1d, 0x96, 0x52, 0x0f, 0x72,
	0x63, 0xde, 0x79, 0xb6, 0xf0, 0xbc, 0x1d, 0xe8, 0xb8, 0x63, 0xcf, 0x55, 0xde, 0x58, 0x32, 0x7e,
	0x96, 0xff, 0x0c, 0xb1, 0x76, 0xe8, 0x85, 0x9c, 0x49, 0x86, 0x20, 0x9f, 0xd8, 0x4f, 0x00, 0x8e,
	0xf2, 0x47, 0xe4, 0x53, 0x11, 0x21, 0xd1, 0x01, 0x34, 0xde, 0x29, 0x17, 0xf2, 0x35, 0x50, 0x3e,
	0x26, 0x7c, 0xc7, 0xd8, 0x37, 0x3a, 0xff, 0x47, 0xf5, 0x78, 0x76, 0x1f, 0x8f, 0xd0, 0x21, 0xac,
	0x0b, 0xe2, 0xb2, 0xe0, 0x2d, 0xc3, 0xfc, 0x8b, 0x31, 0x8d, 0x64, 0x98, 0x80, 0xec, 0x23, 0xa8,
	0xc7, 0xaa, 0x22, 0x64, 0x81, 0x20, 0xc8, 0x84, 0x1a, 0x27, 0x42, 0x79, 0x32, 0x15, 0x4c, 0x4f,
	0x13, 0xf3, 0x21, 0x8d, 0x56, 0x60, 0x1e, 0xab, 0x96, 0x98, 0x3f, 0xc3, 0xe6, 0x9d, 0xf2, 0x24,
	0x0d, 0xbd, 0xaf, 0xbf, 0x4e, 0xd0, 0x85, 0x66, 0x2e, 0x5d, 0xfe, 0x1f, 0x38, 0x0a, 0xaf, 0xa4,
	0x00, 0x5c, 0x6a, 0x7e, 0x05, 0xad, 0x47, 0x4e, 0x7d, 0x92, 0xb0, 0x06, 0xcc, 0x0f, 0x99, 0xa0,
	0x92, 0xb2, 0x20, 0xcb, 0x63, 0x42, 0x6d, 0x2a, 0x49, 0x7a, 0xb2, 0xfb, 0xd0, 0x2e, 0x22, 0x96,
	0x58, 0x9e, 0xc0, 0xd6, 0x04, 0xae, 0x24, 0xb9, 0x8e, 0x3e, 0xca, 0x6c, 0x4e, 0x01, 0xe9, 0xe0,
	0xe5, 0xd2, 0x17, 0xdf, 0x55, 0x68, 0x0e, 0xd2, 0xd5, 0x26, 0x0e, 0xe1, 0x11, 0x75, 0x09, 0xea,
	0x43, 0xd5, 0x51, 0x3e, 0x32, 0x7b, 0xda, 0x67, 0x90, 0x6f, 0xbc, 0xb5, 0x3d, 0x37, 0x4f, 0x4c,
	0xec, 0xca, 0x84, 0x39, 0xa4, 0xd1, 0x34, 0x33, 0x5f, 0xd7, 0x69, 0xa6, 0xb6, 0x70, 0x76, 0x05,
	0xdd, 0xc2, 0x5a, 0xd6, 0x3f, 0xda, 0xd5, 0x61, 0x33, 0x0b, 0x67, 0xed, 0x2d, 0xbe, 0xd4, 0x23,
	0x38, 0x0a, 0xcf, 0x86, 0xc7, 0x05, 0xe1, 0xb1, 0xc6, 0x14, 0x60, 0x2e, 0x2e, 0x08, 0x1d, 0xeb,
	0xa4, 0xa5, 0xed, 0x5b, 0xdd, 0xdf, 0x40, 0x33, 0xcb, 0x73, 0x03, 0x3d, 0x00, 0xe4, 0x75, 0xa1,
	0x96, 0xce, 0x9e, 0xeb, 0xdc, 0x6a, 0x17, 0x5d, 0x67, 0x82, 0x1d, 0xe3, 0x66, 0xe3, 0xa5, 0xa1,
	0x3f, 0x65, 0xb8, 0x16, 0x3f, 0x60, 0x97, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xcf, 0x82,
	0x47, 0xec, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculateServiceClient is the client API for CalculateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculateServiceClient interface {
	// unary rpc services
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	Div(ctx context.Context, in *DivRequest, opts ...grpc.CallOption) (*DivResponse, error)
	Multiply(ctx context.Context, in *MultiplyRequest, opts ...grpc.CallOption) (*MultiplyResponse, error)
	Sub(ctx context.Context, in *SubRequest, opts ...grpc.CallOption) (*SubResponse, error)
	// server streaming rpc services
	PrimeNumberComposition(ctx context.Context, in *PrimeNumberCompositionRequest, opts ...grpc.CallOption) (CalculateService_PrimeNumberCompositionClient, error)
	// client streaming
	ComputeAvg(ctx context.Context, opts ...grpc.CallOption) (CalculateService_ComputeAvgClient, error)
}

type calculateServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculateServiceClient(cc *grpc.ClientConn) CalculateServiceClient {
	return &calculateServiceClient{cc}
}

func (c *calculateServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculateService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculateServiceClient) Div(ctx context.Context, in *DivRequest, opts ...grpc.CallOption) (*DivResponse, error) {
	out := new(DivResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculateService/Div", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculateServiceClient) Multiply(ctx context.Context, in *MultiplyRequest, opts ...grpc.CallOption) (*MultiplyResponse, error) {
	out := new(MultiplyResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculateService/Multiply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculateServiceClient) Sub(ctx context.Context, in *SubRequest, opts ...grpc.CallOption) (*SubResponse, error) {
	out := new(SubResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculateService/Sub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculateServiceClient) PrimeNumberComposition(ctx context.Context, in *PrimeNumberCompositionRequest, opts ...grpc.CallOption) (CalculateService_PrimeNumberCompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculateService_serviceDesc.Streams[0], "/calculator.CalculateService/PrimeNumberComposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculateServicePrimeNumberCompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculateService_PrimeNumberCompositionClient interface {
	Recv() (*PrimeNumberCompositionResponse, error)
	grpc.ClientStream
}

type calculateServicePrimeNumberCompositionClient struct {
	grpc.ClientStream
}

func (x *calculateServicePrimeNumberCompositionClient) Recv() (*PrimeNumberCompositionResponse, error) {
	m := new(PrimeNumberCompositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculateServiceClient) ComputeAvg(ctx context.Context, opts ...grpc.CallOption) (CalculateService_ComputeAvgClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculateService_serviceDesc.Streams[1], "/calculator.CalculateService/ComputeAvg", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculateServiceComputeAvgClient{stream}
	return x, nil
}

type CalculateService_ComputeAvgClient interface {
	Send(*ComputeAvgRequest) error
	CloseAndRecv() (*ComputeAvgResponse, error)
	grpc.ClientStream
}

type calculateServiceComputeAvgClient struct {
	grpc.ClientStream
}

func (x *calculateServiceComputeAvgClient) Send(m *ComputeAvgRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculateServiceComputeAvgClient) CloseAndRecv() (*ComputeAvgResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ComputeAvgResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculateServiceServer is the server API for CalculateService service.
type CalculateServiceServer interface {
	// unary rpc services
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	Div(context.Context, *DivRequest) (*DivResponse, error)
	Multiply(context.Context, *MultiplyRequest) (*MultiplyResponse, error)
	Sub(context.Context, *SubRequest) (*SubResponse, error)
	// server streaming rpc services
	PrimeNumberComposition(*PrimeNumberCompositionRequest, CalculateService_PrimeNumberCompositionServer) error
	// client streaming
	ComputeAvg(CalculateService_ComputeAvgServer) error
}

// UnimplementedCalculateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculateServiceServer struct {
}

func (*UnimplementedCalculateServiceServer) Sum(ctx context.Context, req *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (*UnimplementedCalculateServiceServer) Div(ctx context.Context, req *DivRequest) (*DivResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Div not implemented")
}
func (*UnimplementedCalculateServiceServer) Multiply(ctx context.Context, req *MultiplyRequest) (*MultiplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiply not implemented")
}
func (*UnimplementedCalculateServiceServer) Sub(ctx context.Context, req *SubRequest) (*SubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sub not implemented")
}
func (*UnimplementedCalculateServiceServer) PrimeNumberComposition(req *PrimeNumberCompositionRequest, srv CalculateService_PrimeNumberCompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberComposition not implemented")
}
func (*UnimplementedCalculateServiceServer) ComputeAvg(srv CalculateService_ComputeAvgServer) error {
	return status.Errorf(codes.Unimplemented, "method ComputeAvg not implemented")
}

func RegisterCalculateServiceServer(s *grpc.Server, srv CalculateServiceServer) {
	s.RegisterService(&_CalculateService_serviceDesc, srv)
}

func _CalculateService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculateService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculateService_Div_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DivRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateServiceServer).Div(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculateService/Div",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateServiceServer).Div(ctx, req.(*DivRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculateService_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateServiceServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculateService/Multiply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateServiceServer).Multiply(ctx, req.(*MultiplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculateService_Sub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateServiceServer).Sub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculateService/Sub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateServiceServer).Sub(ctx, req.(*SubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculateService_PrimeNumberComposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberCompositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculateServiceServer).PrimeNumberComposition(m, &calculateServicePrimeNumberCompositionServer{stream})
}

type CalculateService_PrimeNumberCompositionServer interface {
	Send(*PrimeNumberCompositionResponse) error
	grpc.ServerStream
}

type calculateServicePrimeNumberCompositionServer struct {
	grpc.ServerStream
}

func (x *calculateServicePrimeNumberCompositionServer) Send(m *PrimeNumberCompositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculateService_ComputeAvg_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculateServiceServer).ComputeAvg(&calculateServiceComputeAvgServer{stream})
}

type CalculateService_ComputeAvgServer interface {
	SendAndClose(*ComputeAvgResponse) error
	Recv() (*ComputeAvgRequest, error)
	grpc.ServerStream
}

type calculateServiceComputeAvgServer struct {
	grpc.ServerStream
}

func (x *calculateServiceComputeAvgServer) SendAndClose(m *ComputeAvgResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculateServiceComputeAvgServer) Recv() (*ComputeAvgRequest, error) {
	m := new(ComputeAvgRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CalculateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculateService",
	HandlerType: (*CalculateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculateService_Sum_Handler,
		},
		{
			MethodName: "Div",
			Handler:    _CalculateService_Div_Handler,
		},
		{
			MethodName: "Multiply",
			Handler:    _CalculateService_Multiply_Handler,
		},
		{
			MethodName: "Sub",
			Handler:    _CalculateService_Sub_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberComposition",
			Handler:       _CalculateService_PrimeNumberComposition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ComputeAvg",
			Handler:       _CalculateService_ComputeAvg_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}
